### ISSUE TITLE
my mate dmitry said you gapped him

### ISSUE THREAD

**Issue by GyuoMi** [SahilDinanath/RegexEngine#1]
his ass did not teach NFA's

**Comment by SahilDinanath** [comment]
![Alt Text](https://media.discordapp.net/attachments/215541597536780288/979360514683584522/1649359231237.gif?ex=66849b4e&is=668349ce&hm=0541fb88ccb020294ae41bdaa12aba0f795515b3b52c4c35bae55f0df9352c9e&)
